# 네이버 클라우드 플랫폼 설정
ncp:
  access-key: ${NCP_ACCESS_KEY}
  secret-key: ${NCP_SECERET_KEY}
  end-point: https://kr.object.ncloudstorage.com
  region-name: kr-standard
  object-storage:
    bucket-name: fitisland-exercise-image-bucket
    folder-name: images

# 파일 업로드 관련 설정
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
